# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(565, 449)
        Dialog.setStyleSheet("background: qlineargradient(spread:pad, x1:0.006, y1:0, x2:1, y2:1, stop:0 rgba(251, 123, 255, 255), stop:1 rgba(255, 239, 255, 255));")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(190, 10, 181, 101))
        self.label.setStyleSheet("background: rgba(0,0,0,0);\n"
"font: 32pt \"Courier New\";")
        self.label.setObjectName("label")
        self.txt_email = QtWidgets.QLineEdit(Dialog)
        self.txt_email.setGeometry(QtCore.QRect(190, 120, 191, 41))
        self.txt_email.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"\n"
"")
        self.txt_email.setText("")
        self.txt_email.setDragEnabled(False)
        self.txt_email.setReadOnly(False)
        self.txt_email.setObjectName("txt_email")
        self.txt_user = QtWidgets.QLineEdit(Dialog)
        self.txt_user.setGeometry(QtCore.QRect(190, 190, 191, 41))
        self.txt_user.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"\n"
"")
        self.txt_user.setText("")
        self.txt_user.setObjectName("txt_user")
        self.txt_password = QtWidgets.QLineEdit(Dialog)
        self.txt_password.setGeometry(QtCore.QRect(190, 260, 191, 41))
        self.txt_password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"type=\"password\"")
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setObjectName("txt_password")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(190, 100, 47, 13))
        self.label_5.setStyleSheet("background: rgba(0,0,0,0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(190, 170, 47, 13))
        self.label_6.setStyleSheet("background: rgba(0,0,0,0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(190, 240, 47, 13))
        self.label_7.setStyleSheet("background: rgba(0,0,0,0);")
        self.label_7.setObjectName("label_7")
        self.c_showpass = QtWidgets.QCheckBox(Dialog)
        self.c_showpass.setGeometry(QtCore.QRect(190, 310, 70, 17))
        self.c_showpass.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"\n"
"")
        self.c_showpass.setObjectName("c_showpass")
        self.btn_submit = QtWidgets.QPushButton(Dialog)
        self.btn_submit.setGeometry(QtCore.QRect(460, 400, 75, 23))
        self.btn_submit.setObjectName("btn_submit")
        self.label_error = QtWidgets.QLabel(Dialog)
        self.label_error.setGeometry(QtCore.QRect(190, 340, 191, 16))
        self.label_error.setStyleSheet("color:red;\n"
"background-color: rgba(0,0,0,0);")
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.btn_back = QtWidgets.QPushButton(Dialog)
        self.btn_back.setGeometry(QtCore.QRect(30, 400, 75, 23))
        self.btn_back.setObjectName("btn_back")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sign-up"))
        self.label_5.setText(_translate("Dialog", "Email"))
        self.label_6.setText(_translate("Dialog", "User"))
        self.label_7.setText(_translate("Dialog", "Password"))
        self.c_showpass.setText(_translate("Dialog", "Enable "))
        self.btn_submit.setText(_translate("Dialog", "Submit"))
        self.btn_back.setText(_translate("Dialog", "Back"))
