# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(565, 449)
        Dialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.006, y1:0, x2:1, y2:1, stop:0 rgba(251, 123, 255, 255), stop:1 rgba(255, 239, 255, 255));")
        self.txt_login = QtWidgets.QLineEdit(Dialog)
        self.txt_login.setGeometry(QtCore.QRect(190, 164, 191, 41))
        self.txt_login.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"\n"
"")
        self.txt_login.setText("")
        self.txt_login.setObjectName("txt_login")
        self.txt_senha = QtWidgets.QLineEdit(Dialog)
        self.txt_senha.setGeometry(QtCore.QRect(190, 234, 191, 41))
        self.txt_senha.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"\n"
"")
        self.txt_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_senha.setObjectName("txt_senha")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(190, 144, 47, 13))
        self.label.setStyleSheet("background: rgba(0,0,0,0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(190, 214, 47, 13))
        self.label_2.setStyleSheet("background: rgba(0,0,0,0);")
        self.label_2.setObjectName("label_2")
        self.btn_login = QtWidgets.QPushButton(Dialog)
        self.btn_login.setGeometry(QtCore.QRect(190, 314, 75, 23))
        self.btn_login.setStyleSheet("")
        self.btn_login.setObjectName("btn_login")
        self.btn_signup = QtWidgets.QPushButton(Dialog)
        self.btn_signup.setGeometry(QtCore.QRect(310, 314, 71, 23))
        self.btn_signup.setStyleSheet("")
        self.btn_signup.setObjectName("btn_signup")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(220, 20, 131, 91))
        self.label_3.setStyleSheet("font: 32pt \"Courier New\";\n"
"background: rgba(0,0,0,0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(130, 90, 321, 31))
        self.label_4.setStyleSheet("font: 8pt \"Courier New\";\n"
"background: rgba(0,0,0,0);")
        self.label_4.setObjectName("label_4")
        self.label_error = QtWidgets.QLabel(Dialog)
        self.label_error.setGeometry(QtCore.QRect(190, 280, 191, 20))
        self.label_error.setStyleSheet("background: rgba(0,0,0,0);\n"
"color:red;")
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.label.raise_()
        self.txt_login.raise_()
        self.txt_senha.raise_()
        self.label_2.raise_()
        self.btn_login.raise_()
        self.btn_signup.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_error.raise_()

        self.retranslateUi(Dialog)
        self.txt_senha.editingFinished.connect(self.btn_login.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txt_login, self.txt_senha)
        Dialog.setTabOrder(self.txt_senha, self.btn_login)
        Dialog.setTabOrder(self.btn_login, self.btn_signup)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login"))
        self.label.setText(_translate("Dialog", "User"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.btn_login.setText(_translate("Dialog", "Login"))
        self.btn_signup.setText(_translate("Dialog", "Sign Up"))
        self.label_3.setText(_translate("Dialog", "Login"))
        self.label_4.setText(_translate("Dialog", "Sign in to ur existing account or create one."))
